"use client"
import { Provider } from "react-redux";
import store, { RootState } from "@/lib/store";
// export const metadata = {
//   title: 'set up account',
//   description: 'Generated by Live Tech',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider store={store}>
      <body>{children}</body>
      </Provider>
    </html>
  )
}
