import '../app/globals.css'

export const metadata = {
  title: 'লেখার পোকা',
  description: 'Generated by Next.js',
   icons: {
    icon: '/images/logo.png', // /public path
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
