"use client"
import "../../app/globals.css";
import { Provider } from "react-redux";
import store, { RootState } from "@/lib/store";
import { useEffect, useState } from "react";
import NotFound from "@/components/common/nofFound";
// export const metadata = {
//   title: 'set up account',
//   description: 'Generated by Live Tech',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const [userType, setUserType] = useState("");


  // check if user is logged in
  useEffect(() => {
    setUserType(localStorage.getItem("usertype") || "");
  }, []);


  return (
    <html lang="en">
      <Provider store={store}>
        {(localStorage.getItem("usertype")) === "admin" ? <body>{children}</body> : <><NotFound/></>}

      </Provider>
    </html>
  )
}
